import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs'
import Loader from "@/components/Loader";
// import { dark } from '@clerk/themes'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [],
      }}
    >
      <html lang="en">
        <head>
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative mt-[3rem]`}
        >
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <div className="fixed top-0 z-50 w-full">
              <Navbar />
            </div>
            {children}
          </ClerkLoaded>
          <Toaster
            containerClassName="text-xs"
            position="top-center"
            reverseOrder={false}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
